import { ColDef } from "ag-grid-community";
import { PcMain } from "../../../../../models/PcMain";
import { rowIndexValueGetter } from "../../../../../utils/ValueGetters";
import { numberFormatter } from "../../../../../utils/Formaters";
import selectOnFocusNumberEditor from "../../../components/SelectOnFocusNumberEditor";
import { filterDateParams } from "../../../../../utils/Grid";

export const pcMainColDefs: Array<ColDef<PcMain>> = [
  {
    headerName: "#",
    valueGetter: rowIndexValueGetter,
    pinned: "left",
    enableRowGroup: false,
    suppressMenu: true,
    sortable: false,
    filter: false,
  },
  { field: "securityDes", headerName: "Security Des", minWidth: 200 },
  {
    field: "value01CurrentNetExposure",
    headerName: "Exp Val01 Cn",
    aggFunc: "sum",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "currNetPos",
    headerName: "Pos Cn",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "pxBid",
    headerName: "Px Bid",
    minWidth: 100,
    editable: true,
    type: "numericColumn",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
    enableCellChangeFlash: true,
    enableRowGroup: false,
    cellEditor: selectOnFocusNumberEditor,
  },
  {
    field: "bidYield",
    headerName: "Yld Cnv Bid",
    minWidth: 100,
    editable: true,
    type: "numericColumn",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
    enableCellChangeFlash: true,
    enableRowGroup: false,
    cellEditor: selectOnFocusNumberEditor,
  },
  {
    field: "bidSpreadToBenchmark",
    headerName: "Bid Spread To Benchmark",
    editable: true,
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
    cellEditor: selectOnFocusNumberEditor,
  },
  { field: "benchmarkSecurity", headerName: "Bnchmrk Sec Des", minWidth: 100 },
  {
    field: "referenceSecurity1BidSpread",
    headerName: "Ref BM5 Bid Spread",
    editable: true,
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
    cellEditor: selectOnFocusNumberEditor,
  },
  {
    field: "referenceSecurity1",
    headerName: "Ref BM5 Security",
    minWidth: 100,
  },
  {
    field: "bidYieldVsYesterdaysClosingBid",
    headerName: "Bid Yield Vs Yesterdays Closing Bid",
    minWidth: 100,
    aggFunc: "avg",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "pnlCarry",
    headerName: "Pnl Carry",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "lotSize",
    headerName: "Lot Size",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "reserveBax",
    headerName: "Reserve Bax",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "pnlCad",
    headerName: "Pnl CAD",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "realizedProfitAndLoss",
    headerName: "Rlzd Pl",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "unrealizedPnlProposed",
    headerName: "Unrealized Pnl Proposed",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "unrealizedProfitAndLossFromFeeds",
    headerName: "Unrlzd Pl",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "totalBaReserve",
    headerName: "Total BA Reserve",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "totalVolume",
    headerName: "Total Volume",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "askYield",
    headerName: "Yld Cnv Ask",
    minWidth: 100,
    editable: true,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
    cellEditor: selectOnFocusNumberEditor,
  },
  {
    field: "financingRate",
    headerName: "Finance Rt",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "priceBidAskSpread",
    headerName: "Spread Ba Cr",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  { field: "askSpreadType", headerName: "Ask Spread Type", minWidth: 100 },
  {
    field: "askSpread",
    headerName: "Bid Ask Sprd",
    minWidth: 100,
    editable: true,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
    cellEditor: selectOnFocusNumberEditor,
  },
  { field: "cusip", headerName: "Cusip", minWidth: 100 },
  {
    field: "hypotheticalPosition",
    headerName: "Hypothetical Position",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "hypotheticalHedgeEquivalentPosition",
    headerName: "Hypothetical Hedge Equivalent Position",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  { field: "hedgeSecurity", headerName: "Ref BM4 Security", minWidth: 100 },
  { field: "benchmarkPricer", headerName: "Bnchmrk Pricer", minWidth: 100 },
  {
    field: "firmRisk",
    headerName: "Firm Risk",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "value01per1MM",
    headerName: "Val01 Per 1MM",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "yieldBidAskSpread",
    headerName: "Yield Bid Ask Spread",
    editable: true,
    minWidth: 100,
    aggFunc: "avg",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
    cellEditor: selectOnFocusNumberEditor,
  },
  {
    field: "mdBid",
    headerName: "Dur Adj Bid",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "convexityMid",
    headerName: "Cnvx Mid",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "carry",
    headerName: "Carry",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "yesterdaysMarkToMarketPrice",
    headerName: "Yesterday Mtm Price",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "positionStrategyTag1",
    headerName: "Pos Strat Tag 1",
    minWidth: 100,
  },
  { field: "pricingMethod", headerName: "Pricing Method", minWidth: 100 },
  {
    field: "hedgeEquivalentPosition",
    headerName: "Hedge Equivalent Position",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "netFullOpenSettlePosition",
    headerName: "Net Opn Setd Pos",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "projectedSecurityIncome",
    headerName: "Projected Security Income",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "projectedSecurityExpense",
    headerName: "Projected Security Expense",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "netDailyChangeInPosition",
    headerName: "Net Chg Pos",
    minWidth: 100,
    aggFunc: "sum",
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "pnlIncCocInBaseCcy",
    headerName: "Pnl Inc COC In Base Ccy",
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
  },
  {
    field: "pxAsk",
    headerName: "Px Ask",
    editable: true,
    minWidth: 100,
    filter: "agNumberColumnFilter",
    valueFormatter: numberFormatter,
    cellEditor: selectOnFocusNumberEditor,
  },
  { field: "insidePositionNotes2", headerName: "In Pos Nt 2", minWidth: 100 },
  { field: "isin", headerName: "Isin", minWidth: 100 },
  { field: "traderName", headerName: "Trader Name", minWidth: 100 },
  { field: "bbgId59", headerName: "ID BB Unique", minWidth: 100 },
  {
    field: "maturity",
    headerName: "Maturity",
    minWidth: 100,
    filter: "agDateColumnFilter",
    filterParams: filterDateParams,
  },
];
