import { RawMessage } from "./RawMessage";

export type PcMain = Pick<
  RawMessage,
  | "securityDes"
  | "value01CurrentNetExposure"
  | "currNetPos"
  | "pxBid"
  | "bidYield"
  | "bidSpreadToBenchmark"
  | "benchmarkSecurity"
  | "referenceSecurity1BidSpread"
  | "referenceSecurity1"
  | "bidYieldVsYesterdaysClosingBid"
  | "pnlCarry"
  | "lotSize"
  | "reserveBax"
  | "pnlCad"
  | "realizedProfitAndLoss"
  | "unrealizedPnlProposed"
  | "unrealizedProfitAndLossFromFeeds"
  | "totalBaReserve"
  | "totalVolume"
  | "askYield"
  | "financingRate"
  | "priceBidAskSpread"
  | "askSpreadType"
  | "askSpread"
  | "cusip"
  | "hypotheticalPosition"
  | "hypotheticalHedgeEquivalentPosition"
  | "hedgeSecurity"
  | "benchmarkPricer"
  | "firmRisk"
  | "value01per1MM"
  | "yieldBidAskSpread"
  | "mdBid"
  | "convexityMid"
  | "carry"
  | "yesterdaysMarkToMarketPrice"
  | "positionStrategyTag1"
  | "pricingMethod"
  | "hedgeEquivalentPosition"
  | "netFullOpenSettlePosition"
  | "projectedSecurityIncome"
  | "projectedSecurityExpense"
  | "netDailyChangeInPosition"
  | "pnlIncCocInBaseCcy"
  | "pxAsk"
  | "insidePositionNotes2"
  | "isin"
  | "traderName"
  | "bbgId59"
  | "maturity"
>;
